package orukomm.gui.panels;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import orukomm.data.entities.User;
import orukomm.data.repositories.UserRepository;
import orukomm.gui.MainWindow;

public class AdminEditUser extends javax.swing.JPanel {

    private MainWindow parentFrame;
    private ArrayList<User> users;
    private UserRepository userRepo;
    
    private DefaultComboBoxModel<User> cmbModelUsers;
    
    public AdminEditUser(MainWindow parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        userRepo = new UserRepository();
        
        cmbModelUsers = new DefaultComboBoxModel<>();
        cmbUsers.setModel(cmbModelUsers);
        updateComboBoxUsers();
        
    }
    
    private void updateComboBoxUsers() {
        users = userRepo.getAll();
        cmbModelUsers.removeAllElements();

        for (User user : users) {
            cmbModelUsers.addElement(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsers = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<User> cmbUsers;
    // End of variables declaration//GEN-END:variables
}
